services:
  - type: web
    name: kanban-app
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: *.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        value: sqlite:///db/db.sqlite3
    healthCheckPath: /
    autoDeploy: true
