# Generated by Django 4.2.7 on 2025-09-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
