# Generated by Django 4.2.7 on 2025-09-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
