# Generated by Django 4.2.7 on 2025-09-28 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0005_card_archived_list_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('lime', 'Lime'), ('sky', 'Sky'), ('grey', 'Grey')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_backgrounds/'),
        ),
        migrations.AddField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='cover_color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('lime', 'Lime'), ('sky', 'Sky'), ('grey', 'Grey')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='card_covers/'),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('position', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='kanban.board')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('board_data', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='kanban.card')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kanban.customfield')),
            ],
            options={
                'unique_together': {('custom_field', 'card')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('❤️', 'Heart'), ('😂', 'Laughing'), ('😮', 'Surprised'), ('😢', 'Crying'), ('😡', 'Angry'), ('🎉', 'Party'), ('🔥', 'Fire'), ('💯', '100')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='kanban.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('comment', 'user', 'emoji')},
            },
        ),
    ]
